### ISSUE TITLE
Pre-Trained Model

### ISSUE THREAD

**Issue by davidlenz** [bachsh/deep-karaoke-maker#2]
Hey, interesting project! Can you maybe share a pre-trained model? Would be very interesting to see (or hear) some examples.

**Comment by bachsh** [comment]
Hey, to be honest the project is incomplete so I don't have a working trained model. If I were to dive into this project again, I'd implement it with CycleGANs or something similar that translates photos from one domain (histograms) to the other (a binary mask).
